### ISSUE TITLE
[勘误] 第二章

### ISSUE THREAD

**Issue by Cathon** [kuangtu/fixfast#1]
首先感谢莫大把自己FAST协议的理解进行整理出书。
学习的过程中，为莫大做一些勘误校对工作。

“2.4 FIX 消息示例” 中，
> 通常在实际数据传输业务中，一个 FIX 消息中包含了多个重复组，假设市场数据 FIX 消息定义如下：

这一段的 FIX 消息定义，消息示例和通过网站解析出来的表格不太能对的上。

“2.5 FIX 消息字段顺序规则 ” 中，
> minfix 工具【3】

应该对应的第四个参考链接。另外这个`http://elato.se/minifix/ `链接似乎失效了。

**Comment by kuangtu** [comment]
非常感谢！一起做得更好！
1.这一段的 FIX 消息定义，消息示例和通过网站解析出来的表格不太能对的上。
我在网站http://fixdecoder.com/fix_decoder.html 将消息“279=0^269=3^83=1^48=NASDAQ^22=NYS^207=NYS^272=20140730^273=09:14:49^270=1234.123^274=0”（将^替换为|），验证了一下，应该一致。
![image](https://user-images.githubusercontent.com/3457291/61586282-7c4d4080-aba2-11e9-8e80-ec9e44ba4aef.png)，麻烦再确认一下？
2.http://elato.se/minifix/ 链接似乎失效了
我重新找了一下，用这个链接。http://elato.se/minifix/download.html

**Comment by Cathon** [comment]
"2.4 FIX 消息示例" 中的 FIX 消息我是指这一段：
```
35=x|268=2|279=0|269=2|270=9462.50|271=5|48=800123|22=8|1020=10|279=0|269
=0|270=9462.00|271=175|1023=1|48=800123|22=8|1020=15
```
这段 FIX 消息示例上下文的两个表格假设是表一和表二。按照这段 FIX 消息：
1. 表一的标签编号应该依次是 `|279|269|270|271|1023|48|22|1020`
2. 表二中 TAGID=346，应该是1020。

**Comment by kuangtu** [comment]
这个地方描述可能产生了误导，之前作为消息示例，没有完全统一。
我将表一和表二做个统一；
TAGIG=1020。
