### ISSUE TITLE
[勘误] 第三章

### ISSUE THREAD

**Issue by Cathon** [kuangtu/fixfast#2]
` 3.4 字节位序列` 中，

> 对于整数 1024 的二进制表示为：00000111 11011110

我的理解是，1024 的二进制
`‭00000100 00000000‬`
通过停止位编码后
`‭00001000 10000000‬`

不知道是否正确？

**Comment by kuangtu** [comment]
你理解没错。
之前的00000111 11011110的编码，十进制整数位2014，我写成了1024。
同一改为“对于整数1024的二进制表示为：00001000 10000000”
